### ISSUE TITLE
config.h

### ISSUE THREAD

**Issue by arumrum** [NaoNaoMe/ESP8266-WiFi-UART-transparent-bridge#1]
Hello,

Actually i am trying this code, but Config.h is error

Arduino: 1.6.13 (Windows 7), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, 115200, 4M (3M SPIFFS)"

Build options changed, rebuilding all
C:\Users\T400\Documents\Arduino\wifitouart\wifitouart.ino:10:20: fatal error: config.h: No such file or directory

 #include "config.h"

                    ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 0.9 (ESP-12 Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Do you have any suggestion for me? thank you for your help in advance

**Comment by NaoNaoMe** [comment]
Hello arumrum.

Thank you for your interest in my repository.

You might just forget to use "config.h".
This build error said Arduino IDE can not find "config.h" in your source code folder.

So please see ["config.h"](https://github.com/NaoNaoMe/ESP8266-WiFi-UART-transparent-bridge/blob/master/config.h
) in my repository.

Or, Why don't you remove #include "config.h" and add content of the header file in your code.
